seq:
	> resultsSeq.txt
	gcc -std=c99 seqMC2.c -o seqMC.o -lm
	./seqMC.o 100 10 >> resultsSeq.txt
	./seqMC.o 10000 10 >> resultsSeq.txt
	./seqMC.o 1000000 10 >> resultsSeq.txt
	./seqMC.o 100000000 10 >> resultsSeq.txt
	./seqMC.o 1000000000 10 >> resultsSeq.txt